from typing import Protocol

from tegtory.domain.entities import Factory, Product, StorageProduct


class FactoryRepository(Protocol):
    async def get(self, owner_id: int) -> Factory | None: ...
    async def create(self, factory: Factory) -> Factory: ...
    async def update(self, factory: Factory) -> Factory: ...
    async def by_name(self, name: str) -> Factory | None: ...
    async def hire(self, factory_id: int) -> None: ...
    async def upgrade(self, factory_id: int) -> None: ...
    async def set_tax(self, factory_id: int, value: int) -> None: ...
    async def add_available_product(
        self, factory: Factory, product: Product
    ) -> tuple[Factory, Product]: ...
    async def get_available_products(
        self, factory_id: int
    ) -> list[Product]: ...
    async def add_product_in_storage(
        self, storage_product: StorageProduct
    ) -> StorageProduct: ...
