repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.2
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        description: 'Run tests with pytest'
        entry: pytest
        language: python
        types: [ python ]
        require_serial: true
        pass_filenames: false
        always_run: true

      - id: mypy
        name: mypy
        description: 'run mypy'
        entry: mypy .
        language: python
        types: [ python ]
        require_serial: true
        pass_filenames: false
        always_run: true