services:
  bot:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: tegtory-dev
    restart: unless-stopped
  redis:
    image: redis:7
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    restart: always

volumes:
  redis_data: