name: Deploy DEV
on:
  push:
    branches: [ dev ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
        with:
          clean: false
          path: "dev"
      - run: |
          cd dev
          docker compose -f docker/docker-compose.dev.yml up -d --build
