name: Deploy Bot
on: [push]
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: |
          cd /home/tegtory-dev
          docker compose -f docker/docker-compose.dev.yml down 
          docker compose -f docker/docker-compose.dev.yml up -d --build