name: Deploy DEV
on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
        with:
          clean: false
          path: 'Tegtory-prod'
      - run: |
          docker compose -f docker/docker-compose.dev.yml down 
          docker compose -f docker/docker-compose.dev.yml up -d --build
