name: Tegtory Coverage
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"

      - name: check ruff
        run: |
          pip install uv
          uv sync
          uv run python -m grpc_tools.protoc --proto_path=./protos/ --python_out=. --pyi_out=. --grpc_python_out=. protos/tegtory/*.proto
          uv run ruff check .

      - name: check mypy
        run: |
          uv run mypy .

      - name: Test with pytest
        run: |
          uv run pytest