name: Tegtory Coverage
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: "3.13"

    - name: check ruff
      run: |
        pip install ruff
        ruff check .

    - name: check mypy
      run: |
        pip install -r requirements.txt
        mypy .

    - name: Test with pytest
      run: |
        pip install -r requirements.txt
        pytest